### ISSUE TITLE
Error: Vendor response doesn't contain thingArn key in object

### ISSUE THREAD

**Issue by robert-hanuschke** [devops-at-home/cdk-iot-core-certificates#228]
Hi,

when I use the ThingWithCert in the current version ("1.0.213" at time of writing):

```ts
const thingWithCert = new ThingWithCert(this, "ThingWithCert", {
      thingName: "demoThing",
      saveToParamStore: true,
      paramPrefix: "/devices",
    });
```

I get this error during deployment:

`11:04:07 AM | CREATE_FAILED        | AWS::Greengrass::DeviceDefinition   | deviceDefinition
CustomResource attribute error: Vendor response doesn't contain thingArn key in object arn:aws:cloudformation:<region>:<account-id>:stack/<stack-name>/790cfba0-b4f3-11ed-9133-0606d2cf45e0|ThingWithCertlambdaCustomResource28E12CE8|dba2ff30-8d29-46f0-ae82-23843d86be14 in S3 bucket clou
dformation-custom-resource-storage-<region>`

Any idea what I might change to fix this?

**Comment by devops-at-home** [comment]
I've completed testing and everything seems to be working correctly from release `1.0.230` onwards so I'll close this ticket
